# Generated by Django 2.2.16 on 2020-09-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customtext',
            old_name='user',
            new_name='user1',
        ),
        migrations.AlterField(
            model_name='customtext',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
