# Generated by Django 2.2.16 on 2020-09-17 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_auto_20200917_0630"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customtext",
            old_name="user1",
            new_name="user",
        ),
    ]
