# Generated by Django 2.2.16 on 2020-09-17 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200917_0632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customtext',
            old_name='user',
            new_name='profile',
        ),
    ]
