# Generated by Django 2.2.16 on 2020-09-17 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200917_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customtext',
            old_name='title',
            new_name='titleasdfasdf',
        ),
    ]
