# Generated by Django 2.2.16 on 2020-09-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200917_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='JHGjfhg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jhghjghgj', models.BigIntegerField()),
            ],
        ),
    ]
